service: nhi-tw-api

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  env: dev
  profile: goldax
      
functions:
  convertSample:
    handler: functions/convertSample/index.handler
    timeout: 60
    events:
      - http:
          path: convertSample
          method: get
